import WorkspacePreview from "@/components/workspace-preview";

export default function Home() {
  return (<>
<header className="nav wrap"><a className="brand" href="#" aria-label="SPACZE home"><span className="mark">✳</span> SPACZE</a><nav aria-label="Main navigation"><a href="#workspace">Workspace</a><a href="#how">How it works</a><a className="button small" href="#workspace">Explore the demo <span>↗</span></a></nav></header>
<main><section className="hero wrap"><div className="eyebrow"><span className="live-dot"></span> YOUR NEXT CHAPTER STARTS HERE</div><h1>Big ideas.<br />Meet your <em>space.</em></h1><p className="intro">From your first product to your next campaign.<br />One connected workspace to build, launch, and grow your business.</p><div className="hero-actions"><a className="button" href="#workspace">Step inside SPACZE <span>↗</span></a><a className="text-link" href="#how">See how it works <span>↓</span></a></div><p className="caption">An early look at the platform. Built for ambitious founders.</p><div className="orbit" aria-hidden="true"><div className="orbit-ring"></div><div className="orbit-ring two"></div><span className="orbit-core">✳</span><span className="float-label one">An idea worth building ↗</span><span className="float-label second">Your next move, clearer.</span></div></section>
<section className="workspace-section wrap" id="workspace"><div className="section-heading"><div><p className="eyebrow">LESS SWITCHING. MORE BUILDING.</p><h2>Your business, in perspective.</h2></div><span className="demo-badge">INTERACTIVE DEMO · SAMPLE DATA</span></div>
<WorkspacePreview /></section>
<section className="how wrap" id="how"><div><p className="eyebrow">FROM WHAT IF TO WHAT’S NEXT</p><h2>Keep your ambition.<br />Lose the scattered tabs.</h2><p className="section-copy">A connected path from the idea in your head to the business you want to build.</p></div><div className="steps"><article><span>01</span><div><h3>Find your direction.</h3><p>Bring your idea, audience, and goals into a clear working strategy.</p></div></article><article><span>02</span><div><h3>Give your products a home.</h3><p>Organize your catalogue and shape a storefront that feels like your brand.</p></div></article><article><span>03</span><div><h3>Grow with intention.</h3><p>Plan campaigns, review AI suggestions, and approve your next move.</p></div></article></div></section>
<section className="closing wrap"><span className="eyebrow">BUILT AROUND YOUR NEXT MOVE</span><h2>Small beginnings.<br />Wide-open possibilities.</h2><a className="button" href="#workspace">Explore your workspace ↗</a></section></main><footer className="wrap"><a className="brand" href="#">✳ SPACZE</a><p>Make room for what comes next.</p><span>Platform preview · 2026</span></footer>
</>);
}
